## PostgreSQL
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/monetarysdb"
    username: "postgres"
    password: "1234"
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

## DDL
jpa:
  hibernate:
    ddl-auto: none

## Server
server:
  port: 8088
  error:
    whitelabel:
      enabled: false

## ClientProfile service properties
application:
  clientProfileService:
    host: http://clientprofile.internal.anybank.ru
    secret: QWRtaW46YWRtaW4=
    clientInfoByGuidPath: /v1/clientInfoByGUID
    profileNotFoundMessage: 'Не найден профиль клиента'
    accountNotFoundMessage: 'Не найден ни один счёт клиента'
  clientProfileProperties:
    connectionTimeout: 10000
    readTimeout: 30000
    maxConnectionTotal: 1000
    maxConnectionPerRoute: 10
  mqTransferProperties:
    inExchangeName: bank_transfers.in
    outExchangeName: bank_transfers.out
    queueName: bank_transfers.out.monetary
    routingKey: monetarys.rk
  transferMoney:
    payerAccountNotValid: 'Некорректный счёт плательщика'
    payeeGuidNotValid: 'Некорректный идентификатор получателя'
    payeeAccIdNotValid: 'Некорректный идентификатор счёта получателя'
    payeeAccountNotValid: 'Некорректный счёт получателя'
    payeeAccountNotAllowed: 'Невозможно перевести на указанный счёт'
    payeeCardNumberNotValid: 'Некорректный номер карты получателя'
    payeePhoneNotValid: 'Некорректный номер телефона получателя'
    amountNotValid: 'Недопустимая сумма'
    messageToPayeeNotValid: 'Превышена допустимая длина сообщения получателю'
## AVAILABLE DATA
    availableAccountCurrencies: RUB
    availablePayerAccountStatuses: 'work'
    availablePayerAccountTypes: Текущий, Накопительный
    availablePayeeAccountStatuses: 'work'
    availablePayeeAccountTypes: Текущий, Накопительный
    availableCitizenshipCountryCode: 643
    operationCode: 5
    operationCurrency: RUB
    transferDescription: 'В пользу другого клиента'
    phoneNumberRegex: '^[0-9]{10}$'

