## PostgreSQL
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/monetarysdb"
    username: "postgres"
    password: "1234"

## DDL
  jpa:
    hibernate:
      ddl-auto: none

## Server
server:
  port: 8080
  error:
    whitelabel:
      enabled: false